package_id = "pkg"
available_services = []

[config]
domain = "default_val"

[step_states.s1]
state = "done"

[step_states.s1.output]
highlight = false

[step_states.s1.output.config_values]
domain = "default_val"
anidm_oidc_client.output.config_values]
oidc_client_id = "forgejo-client"
