// fsn-llm/src/request.rs — LLM message types and response structs.

use serde::{Deserialize, Serialize};

// ── Role ──────────────────────────────────────────────────────────────────────

/// The role of a participant in an LLM conversation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// The system prompt that sets context and behaviour.
    System,
    /// A message from the human user.
    User,
    /// A reply generated by the assistant.
    Assistant,
}

// ── Message ───────────────────────────────────────────────────────────────────

/// A single message in an LLM conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Who sent this message.
    pub role: Role,
    /// The text content of this message.
    pub content: String,
}

impl Message {
    /// Create a system-role message.
    pub fn system(content: impl Into<String>) -> Self {
        Self { role: Role::System, content: content.into() }
    }

    /// Create a user-role message.
    pub fn user(content: impl Into<String>) -> Self {
        Self { role: Role::User, content: content.into() }
    }

    /// Create an assistant-role message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self { role: Role::Assistant, content: content.into() }
    }
}

// ── TokenUsage ────────────────────────────────────────────────────────────────

/// Token consumption statistics returned by providers that support it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens consumed by the prompt / input.
    pub prompt_tokens: u32,
    /// Tokens generated in the completion / output.
    pub completion_tokens: u32,
}

impl TokenUsage {
    /// Total tokens (prompt + completion).
    pub fn total(&self) -> u32 {
        self.prompt_tokens + self.completion_tokens
    }
}

// ── LlmResponse ───────────────────────────────────────────────────────────────

/// The response returned by an [`LlmProvider`](crate::provider::LlmProvider).
#[derive(Debug, Clone)]
pub struct LlmResponse {
    /// The assistant's reply text.
    pub content: String,
    /// The model identifier used for this response.
    pub model: String,
    /// Token usage, if the provider reports it.
    pub usage: Option<TokenUsage>,
}

impl LlmResponse {
    /// Create a minimal response (no usage data).
    pub fn new(content: impl Into<String>, model: impl Into<String>) -> Self {
        Self { content: content.into(), model: model.into(), usage: None }
    }
}
