//! All FreeSynergy UI components.

pub mod app_launcher;
pub mod badge;
pub mod button;
pub mod card;
pub mod code_block;
pub mod context_menu;
pub mod form;
pub mod help_panel;
pub mod icon_button;
pub mod input;
pub mod lang_switcher;
pub mod llm_chat;
pub mod modal;
pub mod notification;
pub mod progress;
pub mod scroll_container;
pub mod search_bar;
pub mod select;
pub mod sidebar;
pub mod spinner;
pub mod status_bar;
pub mod table;
pub mod tabs;
pub mod theme_switcher;
pub mod toast;
pub mod tooltip;
pub mod window;

pub use app_launcher::{AppEntry, AppLauncher, AppLauncherProps};
pub use badge::{Badge, BadgeProps, BadgeVariant};
pub use button::{Button, ButtonProps, ButtonVariant};
pub use card::{Card, CardProps};
pub use code_block::{CodeBlock, CodeBlockProps};
pub use context_menu::{ContextMenu, ContextMenuProps, MenuItem};
pub use form::{Form, FormProps};
pub use help_panel::{HelpPanel, HelpPanelProps};
pub use icon_button::{IconButton, IconButtonProps};
pub use input::{Input, InputProps};
pub use lang_switcher::{LangOption, LangSwitcher, LangSwitcherProps};
pub use llm_chat::{ChatMessage, LlmChat, LlmChatProps};
pub use modal::{Modal, ModalProps};
pub use notification::{Notification, NotificationLevel, NotificationProps};
pub use progress::{Progress, ProgressProps};
pub use scroll_container::{ScrollContainer, ScrollContainerProps};
pub use search_bar::{SearchBar, SearchBarProps};
pub use select::{Select, SelectOption, SelectProps};
pub use sidebar::{Sidebar, SidebarItem, SidebarProps};
pub use spinner::{Spinner, SpinnerProps, SpinnerSize};
pub use status_bar::{StatusBar, StatusBarProps};
pub use table::{Table, TableProps};
pub use tabs::{TabItem, Tabs, TabsProps};
pub use theme_switcher::{ThemeSwitcher, ThemeSwitcherProps};
pub use toast::{Toast, ToastLevel, ToastProps};
pub use tooltip::{Tooltip, TooltipPosition, TooltipProps};
pub use window::{Window, WindowProps};
