//! Threshold-based alerting for disk, memory, and CPU temperature.
//!
//! `AlertChecker::check_once()` collects live metrics and returns any
//! `SysInfoAlert` values whose thresholds have been exceeded.  The caller
//! (e.g. the `fsn sysinfo --monitor` loop in the CLI) is responsible for
//! publishing alerts to the message bus.
//!
//! Bus topics:
//! - `sysinfo.alert.disk`   — disk partition above threshold
//! - `sysinfo.alert.memory` — RAM usage above threshold
//! - `sysinfo.alert.cpu`    — CPU temperature above threshold
//! - `sysinfo.alert.smart`  — SMART failure detected (feature = "smart")

use serde::{Deserialize, Serialize};

use crate::{DiskInfo, MemInfo, ThermalInfo};

// ── SysInfoAlert ──────────────────────────────────────────────────────────────

/// An alert generated by the system-info monitor.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "type")]
pub enum SysInfoAlert {
    /// A disk partition is above the configured usage threshold.
    DiskFull {
        /// Mount point of the affected partition.
        mount_point: String,
        /// Current usage percentage.
        used_percent: f64,
        /// Configured threshold that was exceeded.
        threshold_percent: f64,
    },
    /// A CPU temperature sensor exceeded the configured threshold.
    CpuHot {
        /// Sensor label.
        sensor: String,
        /// Current temperature in Celsius.
        temp_celsius: f32,
        /// Configured threshold that was exceeded.
        threshold_celsius: f32,
    },
    /// RAM usage is above the configured threshold.
    MemoryFull {
        /// Current usage percentage.
        used_percent: f64,
        /// Configured threshold that was exceeded.
        threshold_percent: f64,
    },
    /// A drive reported a SMART failure.
    #[cfg(feature = "smart")]
    SmartError {
        /// Device path.
        device: String,
        /// SMART assessment string.
        assessment: String,
    },
}

impl SysInfoAlert {
    /// Bus topic for this alert type, e.g. `"sysinfo.alert.disk"`.
    pub fn bus_topic(&self) -> &'static str {
        match self {
            SysInfoAlert::DiskFull { .. } => "sysinfo.alert.disk",
            SysInfoAlert::CpuHot { .. } => "sysinfo.alert.cpu",
            SysInfoAlert::MemoryFull { .. } => "sysinfo.alert.memory",
            #[cfg(feature = "smart")]
            SysInfoAlert::SmartError { .. } => "sysinfo.alert.smart",
        }
    }

    /// Short human-readable description suitable for log output and notifications.
    pub fn description(&self) -> String {
        match self {
            SysInfoAlert::DiskFull {
                mount_point,
                used_percent,
                ..
            } => format!("Disk {mount_point} is {used_percent:.1}% full"),
            SysInfoAlert::CpuHot {
                sensor,
                temp_celsius,
                ..
            } => format!("CPU sensor '{sensor}' is {temp_celsius:.1}°C"),
            SysInfoAlert::MemoryFull { used_percent, .. } => {
                format!("Memory is {used_percent:.1}% used")
            }
            #[cfg(feature = "smart")]
            SysInfoAlert::SmartError { device, assessment } => {
                format!("SMART error on {device}: {assessment}")
            }
        }
    }
}

// ── AlertThresholds ───────────────────────────────────────────────────────────

/// Configurable thresholds for alert generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlertThresholds {
    /// Disk usage percentage that triggers a DiskFull alert (default: 90 %).
    pub disk_full_percent: f64,
    /// CPU temperature in Celsius that triggers a CpuHot alert (default: 85 °C).
    pub cpu_hot_celsius: f32,
    /// Memory usage percentage that triggers a MemoryFull alert (default: 90 %).
    pub memory_full_percent: f64,
}

impl Default for AlertThresholds {
    fn default() -> Self {
        Self {
            disk_full_percent: 90.0,
            cpu_hot_celsius: 85.0,
            memory_full_percent: 90.0,
        }
    }
}

// ── AlertChecker ──────────────────────────────────────────────────────────────

/// Checks live system metrics against `AlertThresholds` and returns any alerts.
#[derive(Default)]
pub struct AlertChecker {
    /// Configured alert thresholds.
    pub thresholds: AlertThresholds,
}

impl AlertChecker {
    /// Create a checker with the given thresholds.
    pub fn new(thresholds: AlertThresholds) -> Self {
        Self { thresholds }
    }

    /// Create a checker with default thresholds.
    pub fn with_defaults() -> Self {
        Self::default()
    }
}

impl AlertChecker {
    /// Run one check cycle: read disk, memory, and CPU temperature, return all triggered alerts.
    pub fn check_once(&self) -> Vec<SysInfoAlert> {
        let mut alerts = Vec::new();

        // ── Disk ─────────────────────────────────────────────────────────────
        let disk = DiskInfo::detect();
        for part in &disk.partitions {
            if part.used_percent() >= self.thresholds.disk_full_percent {
                alerts.push(SysInfoAlert::DiskFull {
                    mount_point: part.mount_point.clone(),
                    used_percent: part.used_percent(),
                    threshold_percent: self.thresholds.disk_full_percent,
                });
            }
        }

        // ── Memory ───────────────────────────────────────────────────────────
        let mem = MemInfo::detect();
        if mem.used_percent() >= self.thresholds.memory_full_percent {
            alerts.push(SysInfoAlert::MemoryFull {
                used_percent: mem.used_percent(),
                threshold_percent: self.thresholds.memory_full_percent,
            });
        }

        // ── CPU temperature ──────────────────────────────────────────────────
        let thermal = ThermalInfo::detect();
        for sensor in &thermal.sensors {
            if sensor.temp_celsius >= self.thresholds.cpu_hot_celsius {
                alerts.push(SysInfoAlert::CpuHot {
                    sensor: sensor.label.clone(),
                    temp_celsius: sensor.temp_celsius,
                    threshold_celsius: self.thresholds.cpu_hot_celsius,
                });
            }
        }

        // ── SMART ────────────────────────────────────────────────────────────
        #[cfg(feature = "smart")]
        {
            let smart = crate::SmartInfo::detect();
            for drive in &smart.drives {
                if !drive.passed {
                    alerts.push(SysInfoAlert::SmartError {
                        device: drive.device.clone(),
                        assessment: drive.assessment.clone(),
                    });
                }
            }
        }

        alerts
    }
}
