// catalog.rs — Catalog<M>, CatalogMeta, LocaleEntry, CatalogCache.
//
// Design pattern: Generic container (Catalog<M>) + project-supplied element
// type (M). The catalog handles lookup and filtering; the element type carries
// all project-specific fields.
//
// catalog.toml structure (per namespace):
//
//   [catalog]       ← CatalogMeta (informational, auto-generated by CI)
//   [[packages]]    ← Vec<M>  (project-supplied type, implements Manifest)
//   [[locales]]     ← Vec<LocaleEntry>
//
// CatalogCache: in-memory TTL cache keyed by "{base_url}/{namespace}".
// Stores raw TOML bytes so any M can be deserialized on demand.

use std::collections::HashMap;
use std::time::{Duration, Instant};

use fsn_error::FsnError;
use serde::{Deserialize, Serialize};

use crate::manifest::Manifest;

// ── CatalogMeta ───────────────────────────────────────────────────────────────

/// The `[catalog]` header block — auto-generated by CI, informational only.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CatalogMeta {
    /// Project or namespace name, e.g. `"Node"`.
    #[serde(default)]
    pub project: String,

    /// Catalog schema version, e.g. `"1.0.0"`.
    #[serde(default)]
    pub version: String,

    /// ISO-8601 timestamp of when this catalog was generated.
    #[serde(default)]
    pub generated_at: String,
}

// ── Catalog<M> ────────────────────────────────────────────────────────────────

/// Generic catalog for any package type `M`.
///
/// Deserializes the `[[packages]]` and `[[locales]]` arrays from a
/// `catalog.toml` file. Projects supply their own `M` type (e.g.
/// `ModuleManifest` for FSN, `PluginManifest` for Wiki.rs).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Catalog<M> {
    /// Catalog metadata — informational, safe to ignore.
    #[serde(default)]
    pub catalog: CatalogMeta,

    /// All packages listed in this catalog.
    #[serde(default = "Vec::new")]
    pub packages: Vec<M>,

    /// All available locale packs listed in this catalog.
    #[serde(default)]
    pub locales: Vec<LocaleEntry>,
}

impl<M> Default for Catalog<M> {
    fn default() -> Self {
        Self {
            catalog: CatalogMeta::default(),
            packages: Vec::new(),
            locales: Vec::new(),
        }
    }
}

impl<M> Catalog<M> {
    /// Parse a catalog from a TOML string.
    pub fn from_toml(s: &str) -> Result<Self, FsnError>
    where
        M: for<'de> Deserialize<'de>,
    {
        toml::from_str(s)
            .map_err(|e| FsnError::parse(format!("catalog parse error: {e}")))
    }

    /// Filter packages whose category starts with `prefix`.
    ///
    /// `"deploy."` matches `"deploy.proxy"`, `"deploy.iam"`, etc.
    pub fn by_category<'a>(&'a self, prefix: &str) -> Vec<&'a M>
    where
        M: Manifest,
    {
        self.packages
            .iter()
            .filter(|p| p.category().starts_with(prefix))
            .collect()
    }

    /// Find a package by exact ID.
    pub fn find(&self, id: &str) -> Option<&M>
    where
        M: Manifest,
    {
        self.packages.iter().find(|p| p.id() == id)
    }
}

// ── LocaleEntry ───────────────────────────────────────────────────────────────

/// One entry in `[[locales]]`.
///
/// Shared across all namespaces — locale metadata is always the same shape.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocaleEntry {
    /// BCP-47 locale code, e.g. `"de"`, `"ar"`, `"pt-br"`.
    pub code: String,

    /// Display name in the locale's own script, e.g. `"Deutsch"`, `"العربية"`.
    pub name: String,

    /// Semver version string.
    #[serde(default = "default_version")]
    pub version: String,

    /// Percentage of keys translated, 0–100. Updated by CI.
    #[serde(default)]
    pub completeness: u8,

    /// Text direction: `"ltr"` or `"rtl"`.
    #[serde(default = "default_direction")]
    pub direction: String,

    /// Translation API version — must match `TRANSLATION_API_VERSION` in the app.
    #[serde(default = "default_api_version")]
    pub api_version: u32,

    /// Store-relative path to the locale directory, e.g. `"Node/i18n/de"`.
    #[serde(default)]
    pub path: Option<String>,

    /// Store-relative path to the locale icon, e.g. `"shared/i18n/de/icon.svg"`.
    #[serde(default)]
    pub icon: Option<String>,
}

impl LocaleEntry {
    /// Returns the path to `ui.toml` within a resolved store root, if known.
    pub fn ui_toml_path(&self, store_root: &std::path::Path) -> Option<std::path::PathBuf> {
        self.path
            .as_ref()
            .map(|p| store_root.join(p).join("ui.toml"))
    }
}

fn default_version() -> String { "1.0.0".into() }
fn default_direction() -> String { "ltr".into() }
fn default_api_version() -> u32 { 1 }

// ── CatalogCache ──────────────────────────────────────────────────────────────

/// In-memory TTL cache for fetched catalog TOML text.
///
/// Keyed by `"{base}/{namespace}"` (the URL or file path used to fetch).
/// Stores raw TOML bytes so any `M` type can be deserialized on demand.
/// Avoids redundant network requests within a single process run.
pub struct CatalogCache {
    /// Cache entries: key → (fetched_at, raw_toml_text)
    entries: HashMap<String, (Instant, String)>,

    /// How long a cached entry remains valid.
    ttl: Duration,
}

impl CatalogCache {
    /// Create a new cache with the given TTL.
    pub fn new(ttl: Duration) -> Self {
        Self {
            entries: HashMap::new(),
            ttl,
        }
    }

    /// Create a cache with a 5-minute TTL (production default).
    pub fn default_ttl() -> Self {
        Self::new(Duration::from_secs(300))
    }

    /// Check whether a cached entry for `key` is still valid.
    pub fn get(&self, key: &str) -> Option<&str> {
        self.entries.get(key).and_then(|(fetched_at, text)| {
            if fetched_at.elapsed() < self.ttl {
                Some(text.as_str())
            } else {
                None
            }
        })
    }

    /// Insert or replace a cached entry.
    pub fn insert(&mut self, key: String, text: String) {
        self.entries.insert(key, (Instant::now(), text));
    }

    /// Evict all expired entries.
    pub fn evict_expired(&mut self) {
        self.entries.retain(|_, (fetched_at, _)| fetched_at.elapsed() < self.ttl);
    }

    /// Remove a specific key from the cache.
    pub fn invalidate(&mut self, key: &str) {
        self.entries.remove(key);
    }
}
